# Configuration for GitHub Repository Settings App
# https://github.com/repository-settings/app

repository:
  # Disable unused features
  has_issues: false
  has_discussions: false
  has_projects: false
  has_wiki: false
  has_downloads: false

  # Enforce squash commit only
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: false

  # Allow auto-merge workflows (e.g. Dependabot)
  allow_auto_merge: true

  # Ensure merged branches are deleted
  delete_branch_on_merge: true

  # Enable vulnerability alerts and fixes
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

rulesets:
  - name: baseline
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "~DEFAULT_BRANCH"
        exclude: []
    rules:
      - type: deletion          # Block branch deletion
      - type: non_fast_forward  # Block force-push
      - type: required_linear_history
      - type: required_signatures
  - name: signed
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "~DEFAULT_BRANCH"
        exclude: []
    rules:
      - type: required_signatures
